# Generated by Django 4.2.3 on 2023-07-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_posts_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.ImageField(default=1, upload_to='media', verbose_name='Фото поста'),
            preserve_default=False,
        ),
    ]
